[platformio]
default_envs = seeed_xiao_esp32c6

[env:seeed_xiao_esp32c6]
platform = platformio/espressif32@^7.0.1
board = seeed_xiao_esp32c6
framework = espidf
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_flags =
  -DCONTROLLER_PRESS_GPIO=21
  -DCONTROLLER_PRESS_ACTIVE_HIGH=1
  -DCONTROLLER_PRESS_MS=250
  -DCONTROLLER_GAP_MS=350
  -DSWITCH_GPIO=2
